/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.3-dev */

#ifndef PB_TESLABMS_CODE_PLATFORMIO_PROJECTS_TESLABMSNANOPB_GSM_SRC_TESLA_BMS_PB_H_INCLUDED
#define PB_TESLABMS_CODE_PLATFORMIO_PROJECTS_TESLABMSNANOPB_GSM_SRC_TESLA_BMS_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
typedef struct _TeslaBMS_Pack {
    bool has_id;
    int32_t id;
    pb_callback_t packName;
    bool has_currentVoltage;
    float currentVoltage;
    bool has_averagePacktemp;
    float averagePacktemp;
} TeslaBMS_Pack;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define TeslaBMS_Pack_init_default               {false, 0, {{NULL}, NULL}, false, 0, false, 0}
#define TeslaBMS_Pack_init_zero                  {false, 0, {{NULL}, NULL}, false, 0, false, 0}

/* Field tags (for use in manual encoding/decoding) */
#define TeslaBMS_Pack_id_tag                     1
#define TeslaBMS_Pack_packName_tag               2
#define TeslaBMS_Pack_currentVoltage_tag         4
#define TeslaBMS_Pack_averagePacktemp_tag        5

/* Struct field encoding specification for nanopb */
#define TeslaBMS_Pack_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, INT32,    id,                1) \
X(a, CALLBACK, OPTIONAL, STRING,   packName,          2) \
X(a, STATIC,   OPTIONAL, FLOAT,    currentVoltage,    4) \
X(a, STATIC,   OPTIONAL, FLOAT,    averagePacktemp,   5)
#define TeslaBMS_Pack_CALLBACK pb_default_field_callback
#define TeslaBMS_Pack_DEFAULT NULL

extern const pb_msgdesc_t TeslaBMS_Pack_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define TeslaBMS_Pack_fields &TeslaBMS_Pack_msg

/* Maximum encoded size of messages (where known) */
/* TeslaBMS_Pack_size depends on runtime parameters */

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
