/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.3-dev */

#include "tesla_bms.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(TeslaBMS_Pack, TeslaBMS_Pack, AUTO)


PB_BIND(TeslaBMS_Pack_Module, TeslaBMS_Pack_Module, AUTO)


PB_BIND(TeslaBMS_Pack_Cell, TeslaBMS_Pack_Cell, AUTO)



